name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: sw.imajiugm.com
        username: ${{ secrets.user }}
        key: ${{ secrets.ssh }}
        port: ${{ secrets.port }}
        passphrase: ${{ secrets.passphrase }}
        script: |
          cd ~/sw.imajiugm.com
          git stash
          git pull --force origin master
          hugo
