name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Build
      run: hugo
    - name: Deploy
      uses: up9cloud/action-rsync@v1.1
      env:
        HOST: sw.imajigum.com
        KEY: ${{secrets.SSH}}
        SOURCE: ./public/
        TARGET: ~/public_html/sw/
        USER: ${{secrets.USER}}
        PORT: ${{secrets.PORT}}
        ARGS: --rtvzP
